name: Trigger Data Transformation in app repo

on:
  push:
    branches:
      - development_backup_cbss-bibls  
    paths:
      - 'data/**'  # Trigger only on changes to data files

jobs:
  trigger_application_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Application Repository Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/srophe/syriaca/dispatches \
            -d '{"event_type":"data_updated"}'
