name: Refresh AWS Credentials

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  refresh-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_SROPHE_ROLE }}
          aws-region: us-east-1
          role-session-name: GitHub-OIDC-data
